### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by 4rcturus** [mishalhossin/Discord-Uploader-Bot#3]
anonfiles closed.

**Comment by mishalhossin** [comment]
askers ?

**Comment by 4rcturus** [comment]
?

**Comment by mishalhossin** [comment]
> ?

![image](https://github.com/mishalhossin/Discord-Uploader-Bot/assets/91066601/7cdbcc26-b21e-48c9-9385-76d64014db5d)
updated to another api
